# Generated by Django 5.2 on 2025-04-18 07:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_investment_investor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='earnings',
            new_name='total_earnings',
        ),
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='investment',
            name='includes_referral_earnings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='total_investment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
