# Generated by Django 5.2 on 2025-04-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_investmentsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
