# Generated by Django 5.2 on 2025-04-18 12:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_investor_available_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pairing',
            old_name='confirmation_date',
            new_name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='confirmation_date',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='includes_referral_earnings',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='matched_at',
        ),
        migrations.RemoveField(
            model_name='pairing',
            name='paired_to',
        ),
        migrations.AddField(
            model_name='investment',
            name='pairing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='api.pairing'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='maturation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('matched', 'Matched'), ('sold', 'Sold')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='api.investor'),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='paired_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='paired_investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='api.investment'),
        ),
    ]
